name: Publish Python ðŸ distributions ðŸ“¦ to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Use PDM to Build and publish Python ðŸ distributions ðŸ“¦ to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install twine
        run: python -m pip install twine

      - name: Build and Publish distribution ðŸ“¦ to PyPI
        env:
           PYPI_USERNAME: "__token__"
           PYPI_PASSWORD: ${{ secrets.__token__ }}
        run: |
            cat > ~/.pypirc << EOF
            [pypi]
            username = $PYPI_USERNAME
            password = $PYPI_PASSWORD
            EOF
            pdm build
            twine upload --skip-existing --repository pypi dist/*

